version: '3.6'

networks:
  localdev:
    name: localdev

services:
    employee-api:
        build: .
        restart: always
        ports:
            - "7000:80"
        depends_on:
            - sql-server
            - redis
        networks:
            - localdev

    sql-server:
        image:  mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        container_name: sql-server
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=enes123456
            - MSSQL_PID=Express
        ports:
            - "1433:1433"
        networks:
            - localdev

    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - localdev